import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import Task from '@/components/Task/Task';
import Navbar from '@/components/Navbar/Navbar';
import { useSelector } from 'react-redux';
import { useDispatch } from 'react-redux';

import PrivateRoute from '@/HOC/private';
import { useEffect } from 'react';
import { fetchTodos } from '@/utils/redux/task';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const dispatch = useDispatch();
  const { todos } = useSelector((state) => state);

  return (
    <>
      <PrivateRoute>
        <Head>
          <title>Task tacker</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={` ${inter.className}`}>
          <Navbar />
          <Task />
        </main>
      </PrivateRoute>
    </>
  );
}

// const encodedStr = encodeURIComponent(str);
// letencoded_url_url = AES.encrypt(str, key).toString();
