"use client";

import { Box, Button, TextField, Typography } from "@mui/material";
import { Formik } from "formik";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

const RegForm = () => {
  const router = useRouter();
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleSubmit = async (event) => {
    event.preventDefault();
    await fetch(`https://fair-tan-drill-suit.cyclic.app/user/register`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ fullName, email, password }),
    })
      .then((response) => response.json())
      .then((data) => {
        if (data.success) {
          router.push("/");
        }
      });
  };

  return (
    <>
      <Head>
        <title>Register Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Formik>
        <Box
          height={"100vh"}
          width={"100vw"}
          display={"flex"}
          alignItems={"center"}
          justifyContent={"center"}
        >
          <form onSubmit={handleSubmit}>
            <Typography
              align="center"
              variant="h5"
              color={"#667780"}
              fontWeight={"bold"}
              marginBottom={"1rem"}
            >
              Register To the Task Tracker
            </Typography>
            <Box display="grid" gap="1rem" width="500px">
              <TextField
                label="Full Name"
                name="fullName"
                value={fullName}
                onChange={(event) => setFullName(event.target.value)}
                fullWidth
              />
              <TextField
                label="Email"
                name="email"
                value={email}
                onChange={(event) => setEmail(event.target.value)}
              />
              <TextField
                label="Password"
                type="password"
                name="password"
                value={password}
                onChange={(event) => setPassword(event.target.value)}
              />
              <TextField
                label="Confirm Password"
                type="password"
                name="confirmPassword"
              />
              {/* BUTTONS */}
              <Box>
                <Button
                  fullWidth
                  sx={{
                    backgroundColor: "#8500FA",
                    color: "#FFFFFF",
                    "&:hover": { color: "#8500FA" },
                  }}
                  onClick={() => {
                    handleSubmit;
                  }}
                >
                  REGISTER
                </Button>

                <Typography
                  sx={{ display: "flex", gap: ".5rem", marginTop: "1rem" }}
                >
                  Don't have an account?
                  <Link href={"/login"}>
                    <Typography
                      sx={{
                        color: "#8500FA",
                      }}
                    >
                      Log In here.
                    </Typography>
                  </Link>
                </Typography>
              </Box>
            </Box>
          </form>
        </Box>
      </Formik>
    </>
  );
};

export default RegForm;
